### ISSUE TITLE
noSQL vs SQL

### ISSUE THREAD

**Issue by tychovk** [rmotr/pyp-questions#7]
Hi guys,

I've read a lot on the net about noSQL vs SQL, but I'd like to hear your ideas and some examples of applications, perhaps. 
- What are the major differences in usability, functional ease-of-use in conjunction with other programs/modules, performance e.g.?
- What are example applications of both where either shines?

@santiagobasulto I heard you have a strong opinion about this - let us hear it :-)

**Comment by santiagobasulto** [comment]
NoSQL is a broad topic which encompasses everything that's not SQL (of course). SQL the language to query [relational databases](https://en.wikipedia.org/wiki/Relational_database) and [relational model](https://en.wikipedia.org/wiki/Relational_model). So basically, NoSQL is NOT-relational DBs.

Defining NoSQL is hard because every NoSQL Database out there is different. Here's a list of different NoSQL systems: [http://nosql-database.org/](http://nosql-database.org/) I'd suggest trying to implement a sample system in a few different models. For example, implementing a simple CRUD system with MySQL, MongoDB, Cassandra, Amazon Dynamo, etc. You'd see clearly the differences.

My opinions were related to MongoDB. And basically is: I don't like it used in the wrong way. I don't like it when people choose MongoDB to basically put on top a relational model. Usually using some fancy mapping system like [mongoose](http://mongoosejs.com/).

**Comment by tychovk** [comment]
Wow, that's closed early. I guess no discussion about this, guys :p

Thanks for the explanantion, Santiago! Do you know of any examples where specific (and which) noSQL would be strictly better?

**Comment by santiagobasulto** [comment]
Oh, no, sorry. I just closed it so it'd not be there open. If you feel like the discussion is open you can re-open it.

Provide examples is hard because it's a subjective. But generally on schemas that change a lot it's useful (MongoDB is a good example). There's a good performance gain too (Dynamo, BigTable, Cassandra). I suggest you to take a look at BigTable.

**Comment by tychovk** [comment]
Haha but I'm exactly asking for that, your subjective opinion ^_^. With MongoDB, if you cosnsider it a good example, in what types of cases would you say it's good practice to use it, and when would it be bad practice?

**Comment by tychovk** [comment]
http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/

This is pretty explanatory.
