### ISSUE TITLE
Most optimal way: how to check if string is a number, if so: make it an integer

### ISSUE THREAD

**Issue by tychovk** [rmotr/pyp-questions#9]
Hi guys,

How would you do this in the most Pythonic way? 

e.g. 

    a_set = {45, "foo", "65", "bar"}
    a_set_adj = set()
    for v in a_set:
        try:
            v = int(v)
            a_set_adj.add(v)
        except ValueError:
            a_set_adj.add(v)
        
    print (a_set_adj)

input:

    a_set = {45, "foo", "65", "bar"}

output:

    a_set_adj = {65, 'foo', 'bar', 45}

**Comment by Djones4822** [comment]
why not use the string isdigit() method? 

    print '5.1'.isdigit() 
    #-> False
    print '51'.isdigit() 
    #-> True
    print 'Foo'.isdigit() 
    #-> False

**Comment by tychovk** [comment]
Exactly, if there's a mixed possibilities for inputs that's there it'll fail. But my solution seems verbose too...

**Comment by Djones4822** [comment]
Hm, well I guess my question is why aren't you in control of how the data is being passed? In my mind, the only time that should be a worry is if you're getting values from a user, at which point couldn't you validate that they're passing correct values that stage, rather than when you're trying to convert them?

But regardless, how about this solution:

    my_valid_set = set([x for x in a_set if isinstace(x, (int, str))])
    my_final_set = set([x for x in a_set if not x.isdigit()]).update(set([int(x) for x in my_valid_set if x.isdigit()]))

**Comment by santiagobasulto** [comment]
I'll modify @Djones4822 answer a bit and do:

```python
def to_int(x):
    try:
        return int(x)
    except ValueError:
        return x

a_set_adj = {to_int(x) for x in a_set}
```
* Please note the set comprehension (https://docs.python.org/2/tutorial/datastructures.html#sets).

**Comment by Djones4822** [comment]
+1 ^

Ooh that's nice, I like that a lot better

**Comment by tychovk** [comment]
That is terrific, this helped a lot guys! This really helps out becoming better coders, I think.

**Comment by santiagobasulto** [comment]
Yes, exactly, collective knowledge. We can all learn from eachother.

**Comment by tychovk** [comment]
@Djones4822 hey, this was about getting values from a user (exactly), when would you validate it then? 

The thing is, I'm working in P3.4, so the result of input() is always a string. I wanted to do two things: check if it's a number, if so: make it a number, and check if it's within range of (..). To check if it's within a specific range of numbers, it needs to be an integer. But if it's (accidentally) not an integer, it gives back an error when you use int(x). 

This is what I currently use:

    def check_range(str_input):
        try:
            int_input = int(str_input)
            if int_input not in range(1,11):
                return False
            else: 
                return int_input
        except (Exception, e):
            return False

**Comment by Djones4822** [comment]
As it stands right now, I would adjust your code a bit. You don't need all of that in the `try` clause since all you're trying to do is recasting the string as an int., and your except statement should probably reference the expected `ValueError` that converting a non-digit string to an int would call.

```python
 def check_range(str_input):
    try:
        int_input = int(str_input)
    except ValueError:
        return False
    
    if int_input not in range(1,11):
        return False
    else: 
         return int_input
```

It's typically more "pythonic" to avoid making your conditionals as small as possible. This can become particularly important if you find yourself repeating a lot of code for a bunch of different conditions - just pull them out at that point.

But what I was saying about validation at the start was really referencing your list of strings and integers. I couldn't imagine a situation where a user is asked to input a list on their own, so I was thinking that at each input you can check if it was entered correctly.

But maybe a simpler approach to what you're trying might be (it might not be suitable for what you're doing):

```python
from string import digits as strdigits

while True:
    user_input = input('What number would you like to enter?\n\n-> ')
    if user_input in strdigits:
        break
    else: 
        print('You suck at entering numbers')
```

The built in string module has constants like ascii_lowercase ascii_uppercase, digits, punctuation, etc, that can be useful. But I realize, maybe this wouldn't be perfect since you want 1-10 (digits gives you 0-9). So maybe you just want to make your own constant that is a list of valid integer strings to input. So maybe adjust to:

```python
strdigits = [str(x) for x in range(1,11)]

def get_input():
    while True:
        user_input = input('What number would you like to enter?\n\n-> ')
        
        if user_input in strdigits:
            return user_input
        else: 
            print('You suck at entering numbers')
```

I love using while loops when getting input from users. They can get cumbersome, and maybe they're not always the best, but it can be an easy way to repeat the `input()` process until they give you want you want. If you use a `while` loop like that outside of a function, instead of `return user_input` you would use a `break` statement to end the inner-most loop.

**Comment by tychovk** [comment]
This is highly informative! I have mainly been using iterating over functions to check a user's input until it's "right", but looks like a smart alternative. 

You would have strdigits as global variable? I'm thinking of even going as far as making the function more generally usable by including a list as an argument:


    def get_check_input(message, not_within_limits_message, limits_list):
        while True:
            user_input = input(message)

            if user_input in limits_list:
                return user_input
            else:
                print (not_within_limits_message)


What do you think about that? Or is it usually better practice to have multiple (but more specific) functions?

**Comment by Djones4822** [comment]
Sure that might work, passing all of those arguments to the function every time seems cumbersome. Maybe use default arguments, but with messages I don't usually assign them to an object - but what do I know. From what I've seen, messages are usually only assigned to an object if they're too long to fit on a line (see PEP-8 80 char limit). 

But also, python scope is nice in that you don't have to worry too much about global objects. Since you're only calling a reference against that object and not trying to alter it at all, you can just reference it easily enough. 

```python
def get_check_input(message, error_message = not_within_limits_message, check_list = limits_list):
    while True:
        user_input = input(message)

        if user_input in check_list:
            return user_input
        else:
            print (error_message)
```

(Pro tip: you can get git hub to format your code blocks by typing ```python on the line before your code and then ending it with  another 3 ticks (```))

**Comment by tychovk** [comment]
You're great. Thanks a bunch. I'm thinking of rather using the first one as you may have different input requests with each their own error message. Great!

**Comment by Djones4822** [comment]
Yea so the first way makes it more versatile. Good for use in a class or static method that would be used in multiple circumstances.

**Comment by vihu** [comment]
Here's my take on this:

```python
a_list = ['65', '65.5', 'hello', 'apple', '65apple', 80]
expected = [65, '65.5', 'hello', 'apple', '65apple', 80]

def checker(sample):
    try:
        return [int(i) if str(i).isdigit() else i for i in sample]
    except Exception, e:
        return Exception('Shit happens', e)

print checker(a_list) == expected
```

**Comment by Djones4822** [comment]
I reeeaaaallly like that list comp you wrote. I didn't know you could write them like that - thanks!
